// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvlthirbqwohkldpvago.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2bHRoaXJicXdvaGtsZHB2YWdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NTg0NjksImV4cCI6MjA3NDIzNDQ2OX0.t1_0vnF-yVMys2I2lHOrjT2awc8s7JUaJuqd-GkeGKc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});